# Generated by Django 5.1.2 on 2024-11-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
